---
title: "school-learning environment"
---

```{r include=FALSE}
setwd("C:/Users/user/Desktop/Aklim analysis")
```

```{r include=FALSE}
library(sandwich)
library(lmtest)
library(stargazer)
library(estimatr)
library(texreg)
library(tidyverse)
library(plm)
library(lfe)
library(estimatr)
```

## Introduction
In this analysis there are 3 models for each school-learning environment analysis: 
Model 1: General DiD with clustered SE at school level 
Model 2: DiD with school and year fixed effects 
Model 3: DiD with school and year fixed effects and additional variables 


```{r include=FALSE}
getwd()
final <- read.csv("final.csv")
```


```{r include=FALSE}
final$CODE_MIGZAR  <- ifelse(final$CODE_MIGZAR == "1", "0", "1")

final_jew <- final %>% 
  filter(CODE_MIGZAR == "0")

final_arb <- final %>% 
  filter(CODE_MIGZAR == "1")
```


### 1. Using computers in language classes 

```{r}
## DiD regression with clustered SE - Jewish sector

didreg.lang.jew <- lm_robust(Lang ~ treat + after + did,
                            data = final_jew, clusters = CODE_MOSAD, se_type = "stata")

didreg.lang.jew.fe <- lm_robust(Lang ~ did, fixed_effects = ~CODE_MOSAD+SHNAT_LIMUD,
                             data = final_jew, clusters = CODE_MOSAD, se_type = "stata")

didreg.lang.jew.fe.vars <- lm_robust(Lang ~ did + CODE_MIN + SHNOT_LIMUD_EM + SHNOT_LIMUD_AV + MISPAR_ACHIM_TSAD_AV_EM + ERETS_LEDA +
                                     SES_index + TALMIDIM + SHNAT_YISUD, fixed_effects = ~CODE_MOSAD+SHNAT_LIMUD,
                                data = final_jew, clusters = CODE_MOSAD, se_type = "stata")


## DiD regression with clustered SE - Jewish sector

didreg.lang.arb <- lm_robust(Lang ~ treat + after + did,
                             data = final_arb, clusters = CODE_MOSAD, se_type = "stata")

didreg.lang.arb.fe <- lm_robust(Lang ~ did, fixed_effects = ~CODE_MOSAD+SHNAT_LIMUD,
                                data = final_arb, clusters = CODE_MOSAD, se_type = "stata")

didreg.lang.arb.fe.vars <- lm_robust(Lang ~ did + CODE_MIN + SHNOT_LIMUD_EM + SHNOT_LIMUD_AV + MISPAR_ACHIM_TSAD_AV_EM + ERETS_LEDA +
                                       SES_index + TALMIDIM + SHNAT_YISUD, fixed_effects = ~CODE_MOSAD+SHNAT_LIMUD,
                                     data = final_arb, clusters = CODE_MOSAD, se_type = "stata")


```




```{r}
screenreg(list(didreg.lang.jew, didreg.lang.jew.fe, didreg.lang.jew.fe.vars, didreg.lang.arb, didreg.lang.arb.fe, didreg.lang.arb.fe.vars),
          custom.header = list("Jewish sector" = 1:3,  "Arab sector" = 4:6), include.ci = F, stars = c(.1, .05, .01), 
          custom.coef.names = c("Intercept", "Treat", "After", "Reform DiD", "Male indicator", "Mother's years of education", "Father's years of education",
                                "Number of siblings", "Native indicator", "SES index", "Class size", "School age"),
          digits = 3, custom.model.names = c("Model 1", "Model 2", "Model 3", "Model 1", "Model 2", "Model 3"))
```

